services:
  fastapi_app:
    build: 
      fastapi_app
    container_name: fastapi_app
    working_dir: /
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./fastapi_app:/fastapi_app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  nextjs_app:
    build:
      nextjs_app
    container_name: nextjs_app
    working_dir: /
    command: npm run dev --prefix nextjs_app
    volumes:
      - ./nextjs_app:/nextjs_app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - fastapi_app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 8888:5432


volumes:
 postgres_data:
    