name: Deploy to GCP

on:
  push:
    branches:
      - deploy-testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build Backend
        run: |
          cd be/teachers-db-rest-demo
          mvn -B package --file pom.xml
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Build Frontend
        run: |
          cd nextjs-app
          npm install
          npm run build
      - name: Configure Nginx
        run: |
          echo "server {
             listen 80;
             server_name your-domain.com;

             location / {
               root /var/www/html/frontend/out;
               try_files $uri $uri/ /index.html;
             }

             location /api {
               proxy_pass http://localhost:8080;
               proxy_set_header Host $host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             }
           }" > /etc/nginx/sites-available/default

      - name: Restart Nginx
        run: systemctl restart nginx

      - name: Upload Frontend
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/out

      - name: Upload Backend Jar
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.29.105.94
          username: venus
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            # Stop any running backend service
            sudo systemctl stop backend-service

            # Upload frontend build
            cp -r /home/runner/work/department-website/frontend/out/* /var/www/html/frontend

            # Upload backend jar
            cp /home/runner/work/department-website/backend/target/*.jar /home/backend/

            # Run backend jar
            cd /home/backend
            nohup java -jar target/*.jar > backend-logs.txt 2>&1 &

            # Start backend service
            sudo systemctl start backend-service
