name: Deploy to GCP

on:
  push:
    branches:
      - change-path-to-npm
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: "17"
      #     distribution: "temurin"
      #     cache: maven

      # - name: Build Backend
      #   run: |
      #     cd be/teachers-db-rest-demo
      #     mvn -B package --file pom.xml

      # - uses: actions/checkout@v2
      # - name: Use Node.js 18.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18.x

      # - name: Build Frontend
      #   run: |
      #     cd nextjs-app
      #     npm install
      #     npm run build

      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: 35.208.215.217
          username: venus
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          script: |
            # Go to app folder
            cd department-website/nextjs-app

            # Stop pm2 process
            pm2 stop 0
            
            # Go to repo folder
            cd ..
            
            # Pull changes from remote origin
            git pull
            
            # Go to app folder
            cd nextjs-app
            
            # Install dependency
            npm install
            
            # Rebuild app
            npm run build
            
            # Restart pm2 process
            pm2 restart 0
